version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped

  vector-db:
    image: chromadb/chroma
    container_name: vector-db
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma
    restart: unless-stopped

  jarvis-backend:
    build:
      context: ./jarvis-backend
      dockerfile: Dockerfile
    container_name: jarvis-backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - vector-db
    volumes:
      - ./jarvis-backend:/app                # Código da API
      - ./chroma_data:/chroma                # Banco vetorial sincronizado
    env_file:
      - .env
    restart: unless-stopped

